Web/Controllers/BookController.cs
using Bll;
using Bll.DB;
using Bll.DTO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Web.Helpers;
using Web.Hubs;

namespace Web.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        // GET: Book
        [AllowAnonymous]
        public ActionResult Index(int pageNumber = 1)
        {
            var model = new BookManager().GetAcceptedBooks(pageNumber, Config.BooksPageSize);
            return View(model);
        }

        // GET: Book/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var model = new BookDetailsViewModel();
            model.Book = new BookManager().GetAcceptedBookById(id);

            if (model.Book != null)
            {
                var ratingManager = new RatingManager();
                model.AverageRating = ratingManager.GetAverageRatingForBook(bookId: id);
                if (User.Identity.IsAuthenticated)
                {
                    model.UserRating = ratingManager.GetRatingForBookByUser(bookId: id, userId: User.Identity.GetUserId());
                }

                model.RatingSelectList = Enumerable.Range(1, 10).Select(n => new SelectListItem
                {
                    Text = n.ToString(),
                    Value = n.ToString(),
                    Selected = n == model.UserRating
                });

                model.RelatedLists = new BookListManager().GetLatestBookListsForBook(id);
                model.Comments = new CommentManager().GetCommentsForBook(id);

                if (TempData.ContainsKey("PostCommentError"))
                {
                    ViewBag.PostCommentError = TempData["PostCommentError"];
                }

                return View(model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        // GET: Book/CoverImage/5
        [AllowAnonymous]
        public ActionResult CoverImage(int id)
        {
            var bookManager = new BookManager();
            var model = User.IsInRole("Admin") ? bookManager.GetBookCoverById(id) : bookManager.GetAcceptedBookCoverById(id);
            if (model != null)
            {
                return new FileContentResult(model, "image/png");
            }
            else
            {
                return HttpNotFound();
            }
        }

        // POST: Book/ListComments/5
        [HttpPost]
        [AllowAnonymous]
        public ActionResult ListComments(int id)
        {
            var model = new CommentManager().GetCommentsForBook(id);
            return PartialView(model);
        }

        // POST: Book/PostComment/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult PostComment(int id, FormCollection collection)
        {
            try
            {
                var comment = new Comment
                {
                    BookId = id,
                    UserId = User.Identity.GetUserId(),
                    Timestamp = DateTime.Now,
                    Text = collection["text"],
                    Status = CommentStatus.Original
                };
                new CommentManager().Create(comment);
                BookHub.UpdateComments(id);
            }
            catch
            {
                TempData["PostCommentError"] = "Posting comment failed!";
            }
            return RedirectToAction("Details", new { id = id });
        }

        // POST: Book/PostRating/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostRating(int id, FormCollection collection)
        {

            int rating;
            if (int.TryParse(collection["rating"], out rating))
            {
                var ratingManager = new RatingManager();
                ratingManager.CreateOrUpdateRatingForBook(id, User.Identity.GetUserId(), rating);

                var averageRating = ratingManager.GetAverageRatingForBook(id);
                BookHub.UpdateRating(id, averageRating);
            }

            return RedirectToAction("Details", new { id = id });
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Book/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var resizedCover = ImageHelper.ResizeImage(model.CoverImage.InputStream, 360, 480);
                var book = new Book
                {
                    Author = model.Author,
                    Title = model.Title,
                    Year = model.Year,
                    Description = model.Description,
                    Cover = resizedCover.GetBuffer(),
                    Status = BookStatus.Pending
                };
                new BookManager().Create(book);

                return RedirectToAction("ThankYou");
            }
            catch (ImageProcessor.Common.Exceptions.ImageFormatException)
            {
                ModelState.AddModelError("CoverImage", "Invalid Cover uploaded");
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Book/ThankYou
        public ActionResult ThankYou()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FilterForList(string q, int listId)
        {
            var model = new BookFilterViewModel
            {
                BookListId = listId,
                FilteredBooks = new BookManager().GetAcceptedBooksByFilterForList(q, listId)
            };
            return PartialView(model);
        }
    }
}

Web/Controllers/ListController.cs
using Bll;
using Bll.DB;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    [Authorize]
    public class ListController : Controller
    {
        // GET: List
        public ActionResult Index()
        {
            var model = new BookListManager().GetBookListsForUser(User.Identity.GetUserId());
            return View(model);
        }

        // GET: List/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var model = new BookListManager().GetBookListById(id);
            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }

        // GET: List/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: List/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookListViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var bookList = new BookList
                {
                    Name = model.Name,
                    Timestamp = DateTime.Now,
                    UserId = User.Identity.GetUserId()
                };
                new BookListManager().Create(bookList);

                return RedirectToAction("Edit", new { id = bookList.Id });
            }
            catch
            {
                return View(model);
            }
        }

        // GET: List/Edit/5
        public ActionResult Edit(int id)
        {
            var model = new BookListManager().GetBookListById(id);

            if (model.UserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
            }

            return View(model);
        }

        // POST: List/AddBook/5?bookId=3
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBook(int id, int bookId)
        {
            var result = new BookListManager().AddBookToList(id, bookId, User.Identity.GetUserId());

            if (result)
            {
                return RedirectToAction("Edit", new { id = id });
            }
            else
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
            }
        }

        // POST: List/RemoveBook/5?bookId=3
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveBook(int id, int bookId)
        {
            var result = new BookListManager().RemoveBookFromList(id, bookId, User.Identity.GetUserId());

            if (result)
            {
                return RedirectToAction("Edit", new { id = id });
            }
            else
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
            }
        }

        // GET: List/Delete/5
        public ActionResult Delete(int id)
        {
            var model = new BookListManager().GetBookListById(id);

            if (model.UserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
            }

            return View(model);
        }

        // POST: List/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                new BookListManager().DeleteBookListForUser(id, User.Identity.GetUserId());

                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError);
            }
        }
    }
}

Web/Views/List/Create.cshtml
@model Web.Models.BookListViewModel

@{
    ViewBag.Title = Resources.LocalizedText.Pages_List_Create;
}

<h2>@Resources.LocalizedText.Pages_List_Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resources.LocalizedText.General_Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/List/Delete.cshtml
@model Bll.DTO.BookListData

@{
    ViewBag.Title = Resources.LocalizedText.General_Delete;
}

<h2>@Model.Name</h2>
<h3>@Resources.LocalizedText.List_Delete_Confirm</h3>

<div>
    <div>
        @if (Model.Entires.Count > 0)
            {
            <ol>
                @foreach (var book in Model.Entires)
                {
                    <li>
                        @if (!string.IsNullOrWhiteSpace(@book.Author))
                        {
                            @book.Author
                            @: &ndash;
                    }
                        @book.Title (@book.Year)
                    </li>
                }
            </ol>

        }
        else
        {
            <div style="margin-bottom: 10px">@Resources.LocalizedText.List_NoEntries</div>
        }
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="btn-group">
            <input type="submit" value="@Resources.LocalizedText.General_Delete" class="btn btn-danger" />
            @Html.ActionLink(Resources.LocalizedText.General_Back, "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
        </div>
    }
</div>

Web/Views/List/Details.cshtml
@model Bll.DTO.BookListData

@{
    ViewBag.Title = string.Format(Resources.LocalizedText.Title_List_Details, Model.Name);
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<div>
    <div>
        @if (Model.Entires.Count > 0)
            {
            <ol>
                @foreach (var book in Model.Entires)
                {
                    <li>
                        <a href="@Url.Action("Details", "Book", new { id = book.Id })">
                            @if (!string.IsNullOrWhiteSpace(@book.Author))
                            {
                                @book.Author
                                @: &ndash;
                            }
                            @book.Title (@book.Year)
                        </a>
                    </li>
                }
            </ol>

        }
        else
        {
            @Resources.LocalizedText.List_NoEntries
        }
    </div>
    <div class="text-muted">
        @Resources.LocalizedText.List_Details_ShareUrl
        @{var shareUrl = new Uri(Context.Request.Url, @Url.Action("Details", new { id = Model.Id })).ToString();}
        <a href="@shareUrl">@shareUrl</a>
    </div>
</div>

Web/Views/List/Edit.cshtml
@model Bll.DTO.BookListData

@{
    ViewBag.Title = @Resources.LocalizedText.General_Edit;
}

<h2>@Model.Name</h2>

@using (Html.BeginForm("RemoveBook", "List"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-2">@Resources.LocalizedText.List_Edit_Entries</label>
            <div class="col-md-10">
                <div class="list-group">
                    @foreach (var book in Model.Entires)
                    {
                        <div class="list-group-item">
                            <button type="submit" formaction="@Url.Action("RemoveBook", "List", new { id = Model.Id, bookId = book.Id })" class="btn btn-danger btn-xs">
                                <span class="fa fa-minus"></span>
                            </button>&ensp;
                            <span>
                                @if (!string.IsNullOrWhiteSpace(@book.Author))
                                {
                                    @book.Author
                                    @: &ndash;
                                }
                                @book.Title (@book.Year)
                            </span>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("AddBook", "List"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-2" for="add-entry-filter">@Resources.LocalizedText.List_Edit_NewEntry</label>
            <div class="col-md-10">
                <input id="add-entry-filter" type="text" class="form-control" placeholder="@Resources.LocalizedText.List_Edit_Filter" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-push-2">
                <div class="list-group" id="add-entry-results"></div>
            </div>
        </div>
    </div>
}

@section Scripts {
    <script>
        $(function () {
            $('#add-entry-filter')
                .on('keyup', function () {
                    var params = { q: $(this).val(), listId: '@Model.Id' };
                    $('#add-entry-results').load('@Url.Action("FilterForList", "Book")', params);
                })
                .trigger('keyup');
        })
    </script>
}

Web/Views/List/Index.cshtml
@model IEnumerable<Bll.DTO.BookListHeaderData>

@{
    ViewBag.Title = Resources.LocalizedText.Pages_Lists;
}

<h2>@Resources.LocalizedText.Pages_Lists</h2>

<p>
    @Html.ActionLink(Resources.LocalizedText.General_Create_New, "Create", null, new {@class="btn btn-primary"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink(Resources.LocalizedText.General_Edit, "Edit", new { id=item.Id }) |
            @Html.ActionLink(Resources.LocalizedText.General_Details, "Details", new { id=item.Id }) |
            @Html.ActionLink(Resources.LocalizedText.General_Delete, "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>