Web/Models/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class BookViewModel
    {
        [Required(ErrorMessageResourceName = "General_Error_Required", ErrorMessageResourceType = typeof(Resources.LocalizedText))]
        [MaxLength(200, ErrorMessageResourceName = "General_Error_MaxLength", ErrorMessageResourceType = typeof(Resources.LocalizedText))]
        [Display(Name = "Book_Title", ResourceType = typeof(Resources.LocalizedText))]
        public string Title { get; set; }

        [Required(ErrorMessageResourceName = "General_Error_Required", ErrorMessageResourceType = typeof(Resources.LocalizedText))]
        [MaxLength(200, ErrorMessageResourceName = "General_Error_MaxLength", ErrorMessageResourceType = typeof(Resources.LocalizedText))]
        [Display(Name = "Book_Author", ResourceType = typeof(Resources.LocalizedText))]
        public string Author { get; set; }

        [Required(ErrorMessageResourceName = "General_Error_Required", ErrorMessageResourceType = typeof(Resources.LocalizedText))]
        [Range(0, 9999, ErrorMessageResourceName = "General_Error_Range", ErrorMessageResourceType = typeof(Resources.LocalizedText))]
        [Display(Name = "Book_Year", ResourceType = typeof(Resources.LocalizedText))]
        public int Year { get; set; }

        [Required(ErrorMessageResourceName = "General_Error_Required", ErrorMessageResourceType = typeof(Resources.LocalizedText))]
        [DataType(DataType.MultilineText)]
        [MaxLength(2000, ErrorMessageResourceName = "General_Error_MaxLength", ErrorMessageResourceType = typeof(Resources.LocalizedText))]
        [Display(Name = "Book_Description", ResourceType = typeof(Resources.LocalizedText))]
        public string Description { get; set; }

        [Required(ErrorMessageResourceName = "General_Error_Required", ErrorMessageResourceType = typeof(Resources.LocalizedText))]
        [DataType(DataType.Upload)]
        [Display(Name = "Book_Cover", ResourceType = typeof(Resources.LocalizedText))]
        public HttpPostedFileBase CoverImage { get; set; }

    }
}

Web/Controllers/BookController.cs
using Bll;
using Bll.DB;
using Bll.DTO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Web.Helpers;
using Web.Hubs;

namespace Web.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        // GET: Book
        [AllowAnonymous]
        public ActionResult Index(int pageNumber = 1)
        {
            var model = new BookManager().GetAcceptedBooks(pageNumber, Config.BooksPageSize);
            return View(model);
        }

        // GET: Book/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var model = new BookDetailsViewModel();
            model.Book = new BookManager().GetAcceptedBookById(id);

            if (model.Book != null)
            {
                var ratingManager = new RatingManager();
                model.AverageRating = ratingManager.GetAverageRatingForBook(bookId: id);
                if (User.Identity.IsAuthenticated)
                {
                    model.UserRating = ratingManager.GetRatingForBookByUser(bookId: id, userId: User.Identity.GetUserId());
                }

                model.RatingSelectList = Enumerable.Range(1, 10).Select(n => new SelectListItem
                {
                    Text = n.ToString(),
                    Value = n.ToString(),
                    Selected = n == model.UserRating
                });

                model.RelatedLists = new BookListManager().GetLatestBookListsForBook(id);
                model.Comments = new CommentManager().GetCommentsForBook(id);

                if (TempData.ContainsKey("PostCommentError"))
                {
                    ViewBag.PostCommentError = TempData["PostCommentError"];
                }

                return View(model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        // GET: Book/CoverImage/5
        [AllowAnonymous]
        public ActionResult CoverImage(int id)
        {
            var bookManager = new BookManager();
            var model = User.IsInRole("Admin") ? bookManager.GetBookCoverById(id) : bookManager.GetAcceptedBookCoverById(id);
            if (model != null)
            {
                return new FileContentResult(model, "image/png");
            }
            else
            {
                return HttpNotFound();
            }
        }

        // POST: Book/ListComments/5
        [HttpPost]
        [AllowAnonymous]
        public ActionResult ListComments(int id)
        {
            var model = new CommentManager().GetCommentsForBook(id);
            return PartialView(model);
        }

        // POST: Book/PostComment/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult PostComment(int id, FormCollection collection)
        {
            try
            {
                var comment = new Comment
                {
                    BookId = id,
                    UserId = User.Identity.GetUserId(),
                    Timestamp = DateTime.Now,
                    Text = collection["text"],
                    Status = CommentStatus.Original
                };
                new CommentManager().Create(comment);
                BookHub.UpdateComments(id);
            }
            catch
            {
                TempData["PostCommentError"] = "Posting comment failed!";
            }
            return RedirectToAction("Details", new { id = id });
        }

        // POST: Book/PostRating/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostRating(int id, FormCollection collection)
        {

            int rating;
            if (int.TryParse(collection["rating"], out rating))
            {
                var ratingManager = new RatingManager();
                ratingManager.CreateOrUpdateRatingForBook(id, User.Identity.GetUserId(), rating);

                var averageRating = ratingManager.GetAverageRatingForBook(id);
                BookHub.UpdateRating(id, averageRating);
            }

            return RedirectToAction("Details", new { id = id });
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Book/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var resizedCover = ImageHelper.ResizeImage(model.CoverImage.InputStream, 360, 480);
                var book = new Book
                {
                    Author = model.Author,
                    Title = model.Title,
                    Year = model.Year,
                    Description = model.Description,
                    Cover = resizedCover.GetBuffer(),
                    Status = BookStatus.Pending
                };
                new BookManager().Create(book);

                return RedirectToAction("ThankYou");
            }
            catch (ImageProcessor.Common.Exceptions.ImageFormatException)
            {
                ModelState.AddModelError("CoverImage", "Invalid Cover uploaded");
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Book/ThankYou
        public ActionResult ThankYou()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FilterForList(string q, int listId)
        {
            var model = new BookFilterViewModel
            {
                BookListId = listId,
                FilteredBooks = new BookManager().GetAcceptedBooksByFilterForList(q, listId)
            };
            return PartialView(model);
        }
    }
}

Web/Controllers/CommentController.cs
using Bll;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Hubs;

namespace Web.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        // POST: Comment/Report/5
        public ActionResult Report(int id)
        {
            var bookId = new CommentManager().GetBookIdForComment(id);
            if (new CommentManager().ReportCommentById(id))
            {
                BookHub.UpdateComments(bookId);
            }
            return RedirectToAction("Details", "Book", new { id = bookId });
        }
    }
}

Web/Controllers/ListController.cs
using Bll;
using Bll.DB;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    [Authorize]
    public class ListController : Controller
    {
        // GET: List
        public ActionResult Index()
        {
            var model = new BookListManager().GetBookListsForUser(User.Identity.GetUserId());
            return View(model);
        }

        // GET: List/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var model = new BookListManager().GetBookListById(id);
            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }

        // GET: List/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: List/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookListViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var bookList = new BookList
                {
                    Name = model.Name,
                    Timestamp = DateTime.Now,
                    UserId = User.Identity.GetUserId()
                };
                new BookListManager().Create(bookList);

                return RedirectToAction("Edit", new { id = bookList.Id });
            }
            catch
            {
                return View(model);
            }
        }

        // GET: List/Edit/5
        public ActionResult Edit(int id)
        {
            var model = new BookListManager().GetBookListById(id);

            if (model.UserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
            }

            return View(model);
        }

        // POST: List/AddBook/5?bookId=3
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBook(int id, int bookId)
        {
            var result = new BookListManager().AddBookToList(id, bookId, User.Identity.GetUserId());

            if (result)
            {
                return RedirectToAction("Edit", new { id = id });
            }
            else
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
            }
        }

        // POST: List/RemoveBook/5?bookId=3
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveBook(int id, int bookId)
        {
            var result = new BookListManager().RemoveBookFromList(id, bookId, User.Identity.GetUserId());

            if (result)
            {
                return RedirectToAction("Edit", new { id = id });
            }
            else
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
            }
        }

        // GET: List/Delete/5
        public ActionResult Delete(int id)
        {
            var model = new BookListManager().GetBookListById(id);

            if (model.UserId != User.Identity.GetUserId())
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
            }

            return View(model);
        }

        // POST: List/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                new BookListManager().DeleteBookListForUser(id, User.Identity.GetUserId());

                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError);
            }
        }
    }
}

Web/Views/Book/Create.cshtml
@model Web.Models.BookViewModel

@{
    ViewBag.Title = Resources.LocalizedText.Pages_Book_Create;
}

<h2>@Resources.LocalizedText.Pages_Book_Create</h2>

@using (Html.BeginForm("Create", "Book", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CoverImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoverImage)
                @Html.ValidationMessageFor(model => model.CoverImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resources.LocalizedText.General_Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web/Views/Book/Details.cshtml
@model Web.Models.BookDetailsViewModel

@{
    ViewBag.Title = string.Format(Resources.LocalizedText.Title_Book_Details, Model.Book.Title);
    var formattedAverageRating = Model.AverageRating.ToString("0.##", System.Globalization.CultureInfo.CurrentUICulture);
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="text-center">
            @Html.DisplayFor(model => model.Book.Title)
            (@Html.DisplayFor(model => model.Book.Year))
        </h4>
    </div>
    <div class="panel-body">
        <div class="col-md-6 text-center">
            <img src="@Url.Action("CoverImage", new { id = Model.Book.Id })" />
        </div>
        <div class="col-md-6">
            <table class="table">
                <tbody>
                    <tr>
                        <td colspan="2">
                            @(Resources.LocalizedText.Book_Author): @Html.DisplayFor(model => model.Book.Author)
                        </td>
                    </tr>
                    <tr>
                        <td style="padding-top: 12px">
                            @(Resources.LocalizedText.Book_Rating): <span id="book-rating">@formattedAverageRating</span>/10
                        </td>
                        <td class="text-right">
                            @if (User.Identity.IsAuthenticated)
                            {
                                using (Html.BeginForm("PostRating", "Book", new { id = Model.Book.Id }, FormMethod.Post, new { @class = "form-inline" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.DropDownList("rating", Model.RatingSelectList, "Rating", new { @class = "form-control input-sm", style = "max-width: 85px" })
                                    <button type="submit" class="btn btn-sm btn-primary">@(Model.UserRating == null ? "Rate" : "Change")</button>
                                }
                            }
                        </td>
                    </tr>
                    @if (Model.RelatedLists.Count > 0)
                    {
                        <tr>
                            <td colspan="2">
                                @(Resources.LocalizedText.Book_RecentLists):
                                <ul class="list-inline">
                                    @foreach (var l in Model.RelatedLists)
                                    {
                                        <li>
                                            @Html.ActionLink(l.Name, "Details", "List", new { id = l.Id }, null)
                                        </li>
                                    }
                                </ul>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td colspan="2">
                            <div style="white-space: pre-line">@Html.DisplayFor(model => model.Book.Description)</div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="list-group">
        <div id="comment-list">
            @Html.Partial("ListComments", Model.Comments)
        </div>

        <div class="list-group-item">
            @if (User.Identity.IsAuthenticated)
            {
                <div class="list-group-item-heading">Write a comment:</div>
                using (Html.BeginForm("PostComment", "Book", new { id = Model.Book.Id }, FormMethod.Post, new { @class = "form-inline" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.TextBox("text", "", htmlAttributes: new { @class = "form-control" })
                    <button type="submit" class="btn btn-primary">Post</button>
                }
                <div class="text-danger">@ViewBag.PostCommentError</div>
            }
            else
            {
                <span class="text-center">You need to be logged in to write a comment.</span>
            }
        </div>

    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("~/signalr/hubs")
    <script type="text/javascript">
        $(function () {
            var bookHub = $.connection.bookHub;

            bookHub.client.updateComments = function () {
                $("#comment-list").load('@Url.Action("ListComments")', {id: @Model.Book.Id});
            };

            bookHub.client.updateRating = function (rating) {
                $("#book-rating").text((Math.round(rating * 100) / 100).toLocaleString());
            };

            $.connection.hub.start().done(function () {
                bookHub.server.joinRoom(@Model.Book.Id);
            });
        });
    </script>
}

Web/Views/Book/FilterForList.cshtml
@model Web.Models.BookFilterViewModel

@foreach (var item in Model.FilteredBooks)
{
    <div class="list-group-item">
        <button type="submit" formaction="@Url.Action("AddBook", "List", new { id = Model.BookListId, bookId = item.Id })" class="btn btn-success btn-xs">
            <span class="fa fa-plus"></span>
        </button>&ensp;
        <span class="form-control-static">
            @if (!string.IsNullOrWhiteSpace(item.Author))
            {
                @Html.DisplayFor(modelItem => item.Author)
                @: &ndash;
            }
            @Html.DisplayFor(modelItem => item.Title) (@Html.DisplayFor(modelItem => item.Year))
        </span>
    </div>
}

Web/Views/Book/Index.cshtml
@using PagedList
@using PagedList.Mvc
@using Web.Helpers.Mvc
@model IPagedList<Bll.DTO.BookHeaderData>

@{
    ViewBag.Title = @Resources.LocalizedText.Pages_Books;
}

<h2>@Resources.LocalizedText.Pages_Books</h2>

<p>
    @Html.ActionLink(Resources.LocalizedText.General_Create_New, "Create", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Year)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("Details", new { id=item.Id })">
                    @Html.DisplayFor(modelItem => item.Title)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Year)
            </td>
        </tr>
    }

</table>

<div class="text-center">
    @Html.PagedListPager(Model, pageNumber => Url.Action("Index", new { pageNumber = pageNumber }), PagingHelper.CustomPagedListRenderOptions)
</div>

Web/Views/Book/ListComments.cshtml
@model IEnumerable<Bll.DTO.CommentData>

@if (Model.Count() > 0)
{
    foreach (var item in Model)
    {
        <div class="list-group-item">
            <div class="row">
                <div class="col-md-4">
                    <span class="fa fa-user"></span>
                    @Html.DisplayFor(modelItem => item.UserName)
                </div>
                <div class="col-md-6">
                    <span class="fa fa-clock-o"></span>
                    @Html.DisplayFor(modelItem => item.Timestamp)
                </div>
                <div class="col-md-2">
                    @if (item.Status == Bll.CommentStatus.Original)
                    {
                        using (Html.BeginForm("Report", "Comment", new { id = item.Id }, FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-warning btn-xs">Report</button>
                        }
                    }
                    else
                    {
                        switch (item.Status)
                        {
                            case Bll.CommentStatus.Reported:
                                <span class="label label-danger">@Resources.LocalizedText.CommentStatus_Reported</span>
                                break;
                            case Bll.CommentStatus.Verified:
                                <span class="label label-success">@Resources.LocalizedText.CommentStatus_Verified</span>
                                break;
                            case Bll.CommentStatus.Edited:
                                <span class="label label-info">@Resources.LocalizedText.CommentStatus_Edited</span>
                                break;
                        }
                        @* @(typeof(Resources.LocalizedText).GetProperty("CommentStatus_" + item.Status.ToString()).GetValue(null)) *@
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @if (item.Status != Bll.CommentStatus.Reported)
                    {
                        @Html.DisplayFor(modelItem => item.Text)
                    }
                    else
                    {
                        @Resources.LocalizedText.Comment_UnderReview
                    }
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="list-group-item">There are no comments</div>
}

Web/Views/Book/ThankYou.cshtml
@{
    ViewBag.Title = "Thank you";
}

<h2>Thank you!</h2>

<p>Thank you for adding a book to the database. It will appear in the book list after administrator approval.</p>